mantener/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

# Importamos nuevas librerias
from django.conf.urls.static import static
from django.conf import settings

# importamos en donde se encuentran las nuevas ligas a utilizar
from main import views


urlpatterns = [
    path("admin/", admin.site.urls),
    # Agregamos los patrones de las ligas que hemos creado
    path('', views.home, name='home'), #con el nombre es como colocarle un ID a la liga
    path('projects/', include('portfolio.urls')), # con esta ruta renderizamos los proyectos
    path('projects2/', views.render_proyects2, name='projects2')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mantener/main/urls.py
from django.urls import path

# importamos el archivo de views y las funciones para poder renderizar
from .views import render_proyects, project_detail, render_proyects2

# variable para identificar el proyecto
app_name = 'blog'
urlpatterns = [
    # cuando visiten la pagina inicial rendericen los proyectos
    path("", render_proyects, name="projects"),
    path("<int:project_id>", project_detail, name='project_detail'),  # Para hacer URL dinamicas por cada proyecto
    #path('projects2', render_proyects2, name="projects2")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

# Importamos nuevas librerias
from django.conf.urls.static import static
from django.conf import settings

# importamos en donde se encuentran las nuevas ligas a utilizar
from portfolio import views


urlpatterns = [
    path("admin/", admin.site.urls),
    # Agregamos los patrones de las ligas que hemos creado
    path("", views.home, name="home"),  # con el nombre es como colocarle un ID a la liga
    path("portfolio/", include("portfolio.urls")),  # con esta ruta renderizamos los proyectos
    path("projects2/", views.render_proyects2, name="projects2"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

# importamos el archivo de views y las funciones para poder renderizar
from .views import render_proyects, project_detail, render_proyects2

# variable para identificar el proyecto
app_name = "blog"
urlpatterns = [
    # cuando visiten la pagina inicial rendericen los proyectos
    path("", render_proyects, name="projects"),
    path("<int:project_id>", project_detail, name="project_detail"),  # Para hacer URL dinamicas por cada proyecto
    path("projects2/", render_proyects2, name = "projects2")
]

mantener/main/models.py
from django.db import models

# Modulos para importar los datos que estaremos guardando
from django.db.models.fields import TextField, CharField, URLField
from django.db.models.fields.files import ImageField

class Main(models.Model):
    """Clase que guarda los datos del usuario"""
    name = CharField(max_length=100)
    image = ImageField(upload_to='main/images/')
    description = TextField(blank=True)
    subtitle = CharField(max_length=300, blank=True)


class Portfolio(models.Model):
    '''Clase con el modelo de datos para el portafolio'''
    title = CharField(max_length=100)
    subtitle = CharField(max_length=300, blank=True)
    main_image = ImageField(upload_to='main/images/')
    second_image = ImageField(upload_to='main/images/', blank=True)
    third_image = ImageField(upload_to='main/images/', blank=True)

    description = TextField()
    url = URLField(blank=True)

portfolio/models.py
from django.db import models

# Modulos para importar los datos que estaremos guardando
from django.db.models.fields import TextField, CharField, URLField
from django.db.models.fields.files import ImageField

from ckeditor.fields import RichTextField

class Main(models.Model):
    """Clase que guarda los datos del usuario"""

    name = CharField(max_length=100)
    image = ImageField(upload_to="main/images/")
    subtitle = CharField(max_length=300, blank=False)
    description = RichTextField(blank=True)
    

class Portfolio(models.Model):
    """Clase con el modelo de datos para el portafolio"""

    title = TextField(max_length=100)
    subtitle = TextField(max_length=300, blank=True)
    main_image = ImageField(upload_to="main/images/")
    second_image = ImageField(upload_to="main/images/", blank=True)
    third_image = ImageField(upload_to="main/images/", blank=True)

    description = RichTextField()
    url = URLField(blank=True)

class Document(models.Model):
    pdf = models.FileField(upload_to='portfolio/')

portfolio/views.py
from django.shortcuts import render, get_object_or_404

# Importamos la consulta a la base de datos
from .models import Main, Portfolio, Document
from django.http import HttpResponse

# Create your views here.
def home(request):
    """Funcion para que nos arroje la pagina de inicio"""
    main = Main.objects.all()
    return render(request, "home.html", {"main": main})

def render_proyects(request):
    """funcion para retornar el template de proyectos"""
    project = Portfolio.objects.all()
    return render(request, "projects.html", {"project": project})

def project_detail(request, project_id):
    """Funcion para renderizar el detalle del proyecto"""
    project = get_object_or_404(Portfolio, pk=project_id)
    return render(request, "projects_detail.html", {"project": project})



def render_proyects2(request):
    """funcion para retornar el template de proyectos"""
    project = Portfolio.objects.all()
    return render(request, "projects2.html", {"project": project})

mantener/main/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous" />  
        
    <!-- Update these with your own fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,900|Source+Sans+Pro:300,900&display=swap" rel="stylesheet">
    
</head>

<body class="text-light bg-black">
    
    {% include 'partials/navbar.html' %}

    <div class="container p-4">

        
    {% block content %}
    {% endblock %}

    </div>

    {% include 'partials/footer.html' %}


</body>

</html>

portfolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}

<!-- Formatos -->
<style>
    .rounded-img {
    border-radius: 50%;
    }
    
    /* Imagen de la escuela */
    .fondo {
    background-color: var(--clr-dark); /* Validar otros colores */
    /*  Editar Imagen  */
    background-image: url(static/UVM.jpg); 
    background-size: 100% 100%;
    background-blend-mode: multiply; 
    color: var(#494747);
    text-align: center;
    }

    /* Separacion entre las diferentes secciones */
    .seccion {
    margin-bottom: 40px;
    }

    /* nombre de color en la presentacion */
    .super-name h1 {
        color: white;
        font-size: 47px;
        font-weight: 900;
        line-height: 1.2;
        margin: 10px 0px 20px;
    }

    span{
        color: #2ecc71;
    }

    .super-name h4 {
        color: #eee;
        font-weight: 400;
        font-size: 17px;
    }

    .super-name p {
        width: 440px;
        max-width: 100%;
        color: #eee;
        font-size: 15px;
        line-height: 1.5;
        margin-bottom: 30px;
    }

</style>



<!-- Presentacion -->
<section id="presentacion" class="seccion mx-auto" style="max-width: 800px; padding: 0 15px;">
    
    {% for i in main %}

    <header class="p-4 row">
        <div class="col-md-4">
            <img src="{{i.image.url}}" alt="{{i.name}}" class="img-fluid rounded-img">
        </div>

        <div class="col-md-8 my-auto super-name">
            <h1>Hola! Soy <span class="input" data-name="{{i.name}}" data-subtitle="{{i.subtitle}}"></span></h1>
        </div>

        <div>
            <p>{{i.description|safe}}</p>
        </div>
    </header>

    {% endfor %}
</section>

<!-- Escuelas -->
<section class="p-4 fondo seccion">

    <h1 class="text-center">Estudios</h1> 
    
    <div class="container text-center">
        <div class="row align-items-center">
            <div class="col">
                
            <h2>Universidad del Valle de México</h2>
            <p class="my-2 h5 text-muted"><strong>Generación 2014 - 2020</strong></p>
            <h4>Licenciatura Diseño Industrial</h4>
            <p>Diseño y elaboracion de objetos funcionales.</p>
            <p>Aplicacion de metodos de investigacion tomando en cuenta los costos, ergonomia y manufactura.</p>
            <p>Implementacion de nuevos materiales, teconologias  dispositivos.</p>
        
            </div>

           <!-- <div class="col">
                <h2>Ironhack Mexico</h2>
                <p class="my-2 h5 text-muted"><strong>Sep 2020 - Mar 2021</strong></p>
                <h4>Data Analytics Bootcamp</h4>
                <p>Análisis de Datos usando Python (Pandas, Numpy), MySQL, Visualización de Información (Tableau, PowerBI, Matplotlib, Seaborn), Creación, evaluación y desarrollo de modelos de ML (SKLearn), Estadística e Inteligencia de Negocios, Limpieza de Datos, API y WebScraping </p>
           
            </div>-->
        </div> 
    </div> 

</section>

<!-- Proyectos -->  
<section class="seccion">
  <h1 style="text-align: center;">Mis Proyectos</h1>
  
  {% include 'projects2.html' %}

</section>


<script type="text/javascript" src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<script>
    var inputs = document.getElementById("presentacion").getElementsByClassName("input");

    for (var i = 0; i < inputs.length; i++) {
        var input = inputs[i];
        var name = input.getAttribute("data-name");
        var subtitle = input.getAttribute("data-subtitle");

        var typed = new Typed(input, {
            strings: [name, subtitle],
            typeSpeed: 60, 
            backSpeed: 50,
            loop: true
        });
    }
</script>
{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
        integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous" />

    <!-- Update these with your own fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,900|Source+Sans+Pro:300,900&display=swap"
        rel="stylesheet">

</head>

<body >

    {% include 'partials/navbar.html' %}


    <div class="container p-4">

        {% block content %}
        {% endblock %}

    </div>

    {% include 'partials/footer.html' %}


</body>

</html>

portfolio/templates/partials/footer.html
{% load static %}

  <footer class="navbar-dark text-white py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p style="text-align: center;">Sígueme en redes sociales</p>
          <ul class="list-unstyled d-flex justify-content-center" style="padding: 0; margin: 0;">
            <li class="me-4"><a href="https://www.linkedin.com/in/rodrigo-fuentes-carb%C3%B3-5858321a2/"><i class="fab fa-linkedin fa-2x text-white"></i></a></li>
            <!--<li class="me-4"><a href="https://github.com/rikrdinii1"><i class="fab fa-github fa-2x text-white"></i></a></li>-->
            <li><a href="https://www.instagram.com/rockothebeast/"><i class="fab fa-instagram fa-2x text-white"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

portfolio/templates/partials/navbar.html
{% load static %}

<head>
  <style>
    /* Boton para descargar el CV */
    button.cv {
      background: black;
      cursor: pointer;
      border: none;
      padding: 8px 12px;
      color: #FFF;
      font-size: 16px;
      font-weight: bold;
      position: relative;
      border-radius: 12px;
      margin-top: 5px;
    }

    button.cv::before {
      content : "";
      position: absolute;
      top: 0;
      left: 0;
      z-index: -1;
      width: 100%;
      height: 100%;
      background: linear-gradient(45deg, red, blue, deeppink, green, purple, red, blue, deeppink, green, purple);
      background-size: 800%;
      border-radius: 10px;
      filter: blur(8px);
      animation: glowing 40s linear infinite;
    }

    @keyframes glowing {
      0% {background-position: 0 0;}
      50% {background-position: 800% 0;}
      100% {background-position: 0 0;}
    }

    .nav-link {
    margin-right: 20px;
    }

  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Rodrigo Fuentes Carbó</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link fw-bold" href="{% url 'blog:projects' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a href="{% static 'C.V. Rodrigo Fuentes 2023.pdf' %}" download>
              <button class="cv fw-bold">Download CV</button>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>  
</body>

portfolio/templates/projects.html
{% extends 'layout.html' %}

{% block content %}

<style>
    
  .kodfun-galeri {
    display: flex;
    height: 20rem;
    gap: 1rem;
    display: flex; /* mostrar las imágenes en una sola fila */
    flex-wrap: wrap; /* permitir que las imágenes se envuelvan si no hay suficiente espacio en la fila */
    justify-content: center; /* centrar las imágenes horizontalmente */
    max-width: 100%;
    margin: 0 auto;
  }
  
  .kodfun-galeri > div {
    flex: 1;
    border-radius: 1rem;
    background-position: center;
    background-repeat: no-repeat;
    background-size: auto 100%;
    transition: all .8s cubic-bezier(.25, .4, .45, 1.4);
    width: 300px;
    height: 300px;
    opacity: .6;
    
  }

  .kodfun-galeri > div img {
    height: 300px;
    width: 600px;
    display: flex;
    object-fit: cover;
  }

  .kodfun-galeri > div:hover {
    flex: 5;
    filter: contrast(120%);
    opacity: 1;
  }
</style>


<h1 style="text-align: center;">Mis Proyectos</h1>

<body>
  <div class="kodfun-galeri">
    {% for i in project %}
      <div>
        <a href="{% url 'blog:project_detail' i.id %}">
          <img src="{{i.main_image.url}}" alt="{{i.title}}" class="img-fluid">
        </a>
      </div>
    {% endfor %}
  </div>
</body>


{% endblock %}

portfolio/templates/projects2.html
{% load static %}

{% block content %}

<style>
  .image-container {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
    gap: 0;
    margin-top: 20px;
    border-radius: 20px;
    overflow: hidden;
    max-width: 350px;
  }
  
  .image-container img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>

<div style="display: flex;">
  <div style="flex: 1; display: flex; align-items: center;">
    <p style="text-align: center;">
      Soy un profesional apasionado por el diseño y la ingeniería de productos con amplia experiencia en el desarrollo de mobiliario clásico, moderno y contemporáneo. Mis habilidades y conocimientos en el diseño y modelado 3D, renderizado, generación de planos de producción y procesos de fabricación me permiten abordar proyectos desde la conceptualización hasta la producción final de manera eficiente y efectiva.
    </p>
  </div>
  <div style="flex: 1;">
    <div class="image-container">
      <a href="{% url 'blog:projects' %}"><img src="{% static 'mesa_juego.jpg' %}" alt="Imagen 1"></a>
      <a href="{% url 'blog:projects' %}"><img src="{% static 'mueble_contemporaneo.jpg' %}" alt="Imagen 2"></a>
      <a href="{% url 'blog:projects' %}"><img src="{% static 'muebles_exterior.jpg' %}" alt="Imagen 3"></a>
      <a href="{% url 'blog:projects' %}"><img src="{% static 'planos.jpg' %}" alt="Imagen 4"></a>
    </div>
  </div>
</div>


{% endblock %}

portfolio/templates/projects_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<style>
    h1,h2,h3 {
        line-height: 1;
        margin: 0;
    }

    .h1-style {
        font-size: 3rem;
    }

    .h2-style {
        font-size: 2.25rem;
    }

    .h3-style {
        font-size: 1.25rem;
    }

    /* Boton para descargar el CV */
    button.cv {
      background: black;
      cursor: pointer;
      border: none;
      padding: 8px 12px;
      color: #FFF;
      font-size: 16px;
      font-weight: bold;
      position: relative;
      border-radius: 12px;
      margin-top: 5px;
    }

    button.cv::before {
      content : "";
      position: absolute;
      top: 0;
      left: 0;
      z-index: -1;
      width: 100%;
      height: 100%;
      background: linear-gradient(45deg, red, blue, deeppink, green, purple, red, blue, deeppink, green, purple);
      background-size: 800%;
      border-radius: 10px;
      filter: blur(8px);
      animation: glowing 40s linear infinite;
    }

    @keyframes glowing {
      0% {background-position: 0 0;}
      50% {background-position: 800% 0;}
      100% {background-position: 0 0;}
    }

    .nav-link {
    margin-right: 20px;
    }

  </style>
<body>
    

    <section class="intro section-format">
        <h1 class="section__title section__title--intro intro h1-style">
            {{project.title}}
        </h1>
        <p class="section__subtitle section__subtitle--intro">{{project.subtitle}}</p>
        <img src={{project.main_image.url}} alt=""
            class="intro__img img-format">
    </section>

    <div class="portfolio-item-individual">

        <img src="{{project.second_image.url}}" alt="" class="img-format">


        {{project.description|safe}}

        {% if project.third_image %}
        <img src="{{project.third_image.url}}" alt="" class="img-format">
        {% endif %}

        <div class="p-4">
        {% if project.url %}
        <a href="{{project.url}}">
            <button class="cv fw-bold" target="_blank" rel="noreferrer">Visita el Proyecto</button>
        </a>
        {% endif %}
        </div>
        
    </div>

</body>

{% endblock %}